### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by xqianwang** [ibotty/kubernetes-sftp#1]
User 1000 does not have permission to run /usr/sbin/sshd

**Comment by ibotty** [comment]
Can you share your deployment/pod? I cannot reproduce.

**Comment by xqianwang** [comment]
sorry, never mind. I was having trouble to exec sshd when start container.  But that was my mistake.  Thanks, dude

**Comment by ibotty** [comment]
Great that it worked out. If you don't mind, please share the steps leading to the error. It might help others.

**Comment by xqianwang** [comment]
One more question. Can you please provide an example of kubernetes yaml or json file for deployment?

**Comment by ibotty** [comment]
I only have a rc handy (I don't have credentials for a kubernetes cluster at this machine), but you should be able to extrapolate easily.

I would be glad if you could send a pull request with a sample deployment ;).

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: sftp
  name: test-sftp
spec:
  replicas: 1
  selector:
    app: sftp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sftp
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: DEBUG
        image: 172.30.183.139:5000/openshift/openssh@sha256:4835ab23c48b8aa307971ea6d5fa8cf7d60537f02bbab6ade5bf9f2978202ff0
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - lsof
            - -tni
            - :2222
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: sshd
        ports:
        - containerPort: 2222
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - lsof
            - -tni
            - :2222
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /home
          name: data
        - mountPath: /etc/host-credentials
          name: hostcreds
        - mountPath: /etc/credentials/user1
          name: user1-creds
        - mountPath: /etc/credentials/user2
          name: user2-creds
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: test-volume
      - name: hostcreds
        secret:
          defaultMode: 420
          secretName: sftp-hostcreds
      - name: user1-creds
        secret:
          defaultMode: 420
          secretName: user1-creds-pub
      - name: user2-creds
        secret:
          defaultMode: 420
          secretName: user2-creds-pub
```
